export const TRANSLATIONS = {
    en: {
        orbit_weapon: "Orbit",
        orbit_desc: "Rotating defensive orbs",
        wand_weapon: "Magic Wand",
        wand_desc: "Shoots nearest enemy",
        aura_weapon: "Aura",
        aura_desc: "Damages area around you",
        settings: "Settings",
        language: "Language / 言語",
        library: "Library",
        weapons: "Weapons",
        skills: "Skills",
        close: "Close",
        time: "Time: ",
        level: "Level: ",
        hp: "HP",
        exp: "EXP",
        game_over: "GAME OVER",
        game_clear: "GAME CLEAR!",
        survived: "Survived: ",
        cleared: "5 Minutes Achieved!",
        retry: "Retry",
        level_up: "Level Up!",
        heal: "Heal 50 Max HP",
        up_dmg: "Weapon Damage Up",
        up_hp: "Max HP +20",
        add_orb: "Add Orb (+1)",
        up_orb_spd: "Orb Speed Up",
        add_proj: "Add Projectile (+1)",
        up_fire: "Fire Rate Up",
        up_aura_size: "Aura Size Up",
        up_aura_dmg: "Aura Dmg Frequency Up",
        up_magnet: "Magnet Radius Up",
        knife_weapon: "Knife",
        knife_desc: "Fast throwing knives",
        holy_water_weapon: "Holy Water",
        holy_water_desc: "Burns area on ground",
        lightning_weapon: "Lightning",
        lightning_desc: "Chain lightning attack",
        add_knife: "Knife +1",
        add_lightning_chain: "Chain Target +1",
        desc_damage_up: "Damage +20%",
        desc_speed_up: "Attack Speed +20%",
        desc_area_up: "Attack Area +20%",
        desc_size_up: "Size +25%",
        desc_count_up: "Amount +1",
        desc_chain_up: "Chain +1",
        desc_duration_up: "Duration +30%",
        upgrade: "UPGRADE",
        skill_muscle: "Spinach",
        skill_heart: "Hollow Heart",
        skill_tome: "Empty Tome",
        skill_scope: "Candelabrador",
        skill_duplicator: "Duplicator",
        skill_magnet: "Attractorb",
        skill_muscle_desc: "Increases damage by 10%.",
        skill_heart_desc: "Increases max HP by 20%.",
        skill_tome_desc: "Reduces cooldown by 10%.",
        skill_scope_desc: "Increases area by 10%.",
        skill_duplicator_desc: "Increases amount of shots.",
        skill_magnet_desc: "Increases magnet radius by 25%.",
        desc_dmg_10: "Damage +10%",
        desc_hp_20: "Max HP +20%",
        desc_area_10: "Area +10%",
        desc_amount_1: "Amount +1",
        desc_amount_0: "Effect Continue",
        desc_magnet_25: "Magnet +25%",
        skill_wings: "Wings",
        skill_crown: "Crown",
        skill_armor: "Armor",
        skill_pummarola: "Pummarola",
        skill_bracer: "Bracer",
        skill_spellbinder: "Spellbinder",
        skill_wings_desc: "Increases move speed by 10%.",
        skill_crown_desc: "Increases exp gain by 10%.",
        skill_armor_desc: "Reduces damage taken by 1.",
        skill_pummarola_desc: "Regenerates 0.2 HP per second.",
        skill_bracer_desc: "Increases projectile speed by 10%.",
        skill_spellbinder_desc: "Increases weapon duration by 10%.",
        desc_move_speed_10: "Move Speed +10%",
        desc_exp_10: "Exp Gain +10%",
        desc_armor_1: "Armor +1",
        desc_regen_02: "Regen +0.2/sec",
        desc_proj_speed_10: "Proj Speed +10%",
        desc_duration_10: "Duration +10%",
        settings_show_dmg: "Show Damage: ON",
        settings_hide_dmg: "Show Damage: OFF",
        affects: "Affects: ",
        scope_all: "All Weapons",
        scope_player: "Player",
        scope_proj: "Projectiles",
        scope_duration: "Duration Weapons",
        scope_muscle: "scope_all",
        scope_heart: "scope_player",
        scope_tome: "scope_all",
        scope_scope: "scope_all",
        scope_duplicator: "scope_all",
        scope_magnet: "scope_player",
        scope_wings: "scope_player",
        scope_crown: "scope_player",
        scope_armor: "scope_player",
        scope_pummarola: "scope_player",
        scope_bracer: "scope_proj",
        scope_spellbinder: "scope_duration",
        upgrade_count: "Count",
        upgrade_damage: "Damage",
        upgrade_area: "Area",
        upgrade_damage_flat: "Dmg",
        upgrade_speed: "Speed",
        upgrade_amount: "Amount",
        upgrade_duration: "Duration",
        skill_muscle_up: "Damage",
        skill_heart_up: "HP",
        skill_tome_up: "Speed",
        skill_scope_up: "Area",
        skill_duplicator_up: "Amount",
        skill_magnet_up: "Magnet",
        skill_wings_up: "Speed",
        skill_crown_up: "Exp",
        skill_armor_up: "Armor",
        skill_pummarola_up: "Regen",
        skill_bracer_up: "Speed",
        skill_spellbinder_up: "Duration",
        label_weapon: "WEAPON",
        label_skill: "PASSIVE",
        select_character: "Select Your Character",
        char_knight: "Knight",
        char_rogue: "Rogue",
        char_mage: "Mage",
        char_knight_desc: "High HP & Armor",
        char_rogue_desc: "High Speed & Magnet",
        char_mage_desc: "High Damage & Cooldown",
        stat_hp_label: "HP",
        stat_atk_dmg_label: "Atk Damage",
        stat_atk_freq_label: "Atk Frequency",
        stat_move_speed_label: "Move Speed",
        stat_atk_speed_label: "Atk Speed",
        stat_armor_label: "Armor",
        stat_magnet_label: "Magnet",
        rarity_common: "COMMON",
        rarity_uncommon: "UNCOMMON",
        rarity_great: "GREAT",
        rarity_legend: "LEGEND",
        bgm_volume: "BGM Volume",
        sfx_volume: "SFX Volume",
        reroll: "Reroll",
        reroll_remaining: "Remaining: ",
        start_game: "START GAME",
        game_title: "BLOOD SURVIVOR",
        select_weapon: "Select Weapon",
        choose_start_weapon: "Choose your starting weapon:"
    },
    ja: {
        orbit_weapon: "オービット",
        orbit_desc: "周囲を回転する防御オーブ",
        wand_weapon: "マジックワンド",
        wand_desc: "近くの敵を攻撃",
        aura_weapon: "オーラ",
        aura_desc: "周囲のエリアにダメージ",
        settings: "設定",
        language: "言語 / Language",
        library: "ライブラリ",
        weapons: "武器",
        skills: "スキル",
        close: "閉じる",
        time: "時間: ",
        level: "レベル: ",
        hp: "体力",
        exp: "経験値",
        game_over: "ゲームオーバー",
        game_clear: "ゲームクリア！",
        survived: "生存時間: ",
        cleared: "5分間生存達成！",
        retry: "リトライ",
        level_up: "レベルアップ!",
        heal: "最大HPの50回復",
        up_dmg: "武器ダメージ強化",
        up_hp: "最大HP増加 (+20)",
        add_orb: "オーブ追加 (+1)",
        up_orb_spd: "オーブ速度上昇",
        add_proj: "弾数追加 (+1)",
        up_fire: "発射速度上昇",
        up_aura_size: "オーラ範囲拡大",
        up_aura_dmg: "オーラダメージ頻度上昇",
        up_magnet: "経験値回収範囲拡大",
        knife_weapon: "ナイフ",
        knife_desc: "高速投げナイフ",
        holy_water_weapon: "聖水",
        holy_water_desc: "地面にダメージエリアを生成",
        lightning_weapon: "ライトニング",
        lightning_desc: "連鎖雷撃",
        add_knife: "ナイフ+1",
        add_lightning_chain: "連鎖対象+1",
        desc_damage_up: "ダメージ +20%",
        desc_speed_up: "攻撃速度 +20%",
        desc_area_up: "攻撃範囲 +20%",
        desc_size_up: "サイズ +25%",
        desc_count_up: "発射数 +1",
        desc_chain_up: "連鎖数 +1",
        desc_duration_up: "持続時間 +30%",
        upgrade: "強化",
        skill_muscle: "ほうれん草",
        skill_heart: "愛の心",
        skill_tome: "空白の書",
        skill_scope: "ロウソク",
        skill_duplicator: "複写の輪",
        skill_magnet: "磁石",
        skill_muscle_desc: "ダメージを10%上昇させる。",
        skill_heart_desc: "最大HPを20%上昇させる。",
        skill_tome_desc: "クールダウンを10%短縮する。",
        skill_scope_desc: "攻撃範囲を10%拡大する。",
        skill_duplicator_desc: "発射数を増加させる。",
        skill_magnet_desc: "回収範囲を25%拡大する。",
        desc_dmg_10: "ダメージ +10%",
        desc_hp_20: "最大HP +20%",
        desc_area_10: "範囲 +10%",
        desc_amount_1: "発射数 +1",
        desc_amount_0: "効果継続",
        desc_magnet_25: "回収範囲 +25%",
        skill_wings: "翼",
        skill_crown: "王冠",
        skill_armor: "鎧",
        skill_pummarola: "プンマローラ",
        skill_bracer: "手甲",
        skill_spellbinder: "呪文の縛り",
        skill_wings_desc: "移動速度が10%上昇する。",
        skill_crown_desc: "獲得経験値が10%増加する。",
        skill_armor_desc: "受けるダメージを1減少させる。",
        skill_pummarola_desc: "毎秒0.2HP回復する。",
        skill_bracer_desc: "発射物の速度が10%上昇する。",
        skill_spellbinder_desc: "武器の効果時間が10%延長される。",
        desc_move_speed_10: "移動速度 +10%",
        desc_exp_10: "経験値 +10%",
        desc_armor_1: "防御力 +1",
        desc_regen_02: "回復 +0.2/秒",
        desc_proj_speed_10: "弾速 +10%",
        desc_duration_10: "効果時間 +10%",
        settings_show_dmg: "ダメージ表示: ON",
        settings_hide_dmg: "ダメージ表示: OFF",
        affects: "対象: ",
        scope_all: "全武器",
        scope_player: "プレイヤー",
        scope_proj: "発射物",
        scope_duration: "持続系武器",
        scope_muscle: "scope_all",
        scope_heart: "scope_player",
        scope_tome: "scope_all",
        scope_scope: "scope_all",
        scope_duplicator: "scope_all",
        scope_magnet: "scope_player",
        scope_wings: "scope_player",
        scope_crown: "scope_player",
        scope_armor: "scope_player",
        scope_pummarola: "scope_player",
        scope_bracer: "scope_proj",
        scope_spellbinder: "scope_duration",
        upgrade_count: "個数",
        upgrade_damage: "ダメージ",
        upgrade_area: "範囲",
        upgrade_damage_flat: "ダメージ",
        upgrade_speed: "速度",
        upgrade_amount: "発射数",
        upgrade_duration: "時間",
        skill_muscle_up: "威力",
        skill_heart_up: "HP",
        skill_tome_up: "速度",
        skill_scope_up: "範囲",
        skill_duplicator_up: "個数",
        skill_magnet_up: "磁石",
        skill_wings_up: "速度",
        skill_crown_up: "経験値",
        skill_armor_up: "防御",
        skill_pummarola_up: "回復",
        skill_bracer_up: "速度",
        skill_spellbinder_up: "時間",
        label_weapon: "武器",
        label_skill: "パッシブ",
        select_character: "キャラクターを選択",
        char_knight: "騎士",
        char_rogue: "盗賊",
        char_mage: "魔法使い",
        char_knight_desc: "高いHPと防御力を持つ",
        char_rogue_desc: "移動速度と回収範囲に優れる",
        char_mage_desc: "高い攻撃力と攻撃頻度を誇る",
        stat_hp_label: "HP",
        stat_atk_dmg_label: "攻撃力",
        stat_atk_freq_label: "攻撃頻度",
        stat_move_speed_label: "移動速度",
        stat_atk_speed_label: "攻撃速度",
        stat_armor_label: "防御",
        stat_magnet_label: "回収",
        rarity_common: "コモン",
        rarity_uncommon: "アンコモン",
        rarity_great: "グレート",
        rarity_legend: "レジェンド",
        bgm_volume: "BGM音量",
        sfx_volume: "SE音量",
        reroll: "リロール",
        reroll_remaining: "残り: ",
        start_game: "ゲーム開始",
        game_title: "ブラッド・サバイバー",
        select_weapon: "武器の選択",
        choose_start_weapon: "最初の武器を選択してください:"
    }
};

let currentLang = 'ja';

export function t(key) {
    return TRANSLATIONS[currentLang][key] || key;
}

export function getCurrentLang() {
    return currentLang;
}

export function setCurrentLang(lang) {
    currentLang = lang;
}

export function updateTexts(gameTime, gameState) {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        el.innerText = t(key);
    });
    if (gameState && gameState.player) {
        document.getElementById('level').innerText = `${t('level')}${gameState.player.level}`;
        document.getElementById('time').innerText = `${t('time')}${Math.floor(gameTime)}`;
    }
}
